### ISSUE TITLE
How can i Nested Scroll Vertical inside ScrollRectEx Horizontal

### ISSUE THREAD

**Issue by takaaptech** [mob-sakai/ScrollEx#2]
Hi! 
I like this plugin so much! Snap-on end drag feature is awesome!
Now I want to nested a scroll by verticle inside each item of ScrollrectEx horizontal
(For example, each item is one stage 
![screenshot_2018-01-18-11-33-21-332_com gamestart oneline](https://user-images.githubusercontent.com/6276251/35080962-903cb590-fc43-11e7-8e65-9582fc570a2f.png)
and inside it is many levels)
How can I do it? Could you please give me an example scene, thank so much!

**Comment by mob-sakai** [comment]
Hi, @takaaptech !

Thank you for using this plugin.
Please wait a moment!

**Comment by mob-sakai** [comment]
I'm happy to hear that 😄 

> Could you please add Indicator and Navigator to Scrollbar Horizontal so that I can follow it

All right.Ok.

[unitypackage](https://github.com/mob-sakai/ScrollEx/raw/master/ScrollEx.unitypackage).

**Comment by takaaptech** [comment]
It works like a charm! Thank so much!
